spring:
  application:
    name: spring-boot-kotlin-STT

  datasource:
    url: jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:5432/postgres?user\=postgres.qtmqktlmcnuelobniwne
    username: "postgres"
    password: POSTGRES_PASSWORD=cBRghqxtqCbSlI8b
    driver-class-name: org.postgresql.Driver

logging:
  level:
    com.StudentsToThemes.spring_boot_kotlin_STT: DEBUG
    org.springframework: INFO
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
  file:
    name: "application.log"

server:
  port: ${PORT:8080}